# Generated by Django 3.1 on 2020-08-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nome')),
                ('date', models.DateField()),
                ('text', models.CharField(max_length=280, verbose_name='Nome')),
            ],
        ),
    ]
