# Generated by Django 3.1 on 2020-08-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototipo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='name',
        ),
        migrations.AddField(
            model_name='tweets',
            name='link',
            field=models.CharField(default=' ', max_length=280, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='tweets',
            name='user',
            field=models.CharField(default='lala', max_length=20, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='text',
            field=models.CharField(max_length=280, verbose_name='Tweet'),
        ),
    ]
